### ISSUE TITLE
Infinite loop on an invalid token error

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/vaadin-connect#102] opened 2018-12-04 08:29 UTC
* start `vaadin-connect-demo` with `yarn start`
* first, open http://localhost:8000 and wait for the response
* then go to http://localhost:8001 and click any button

Expected: the token is received without any issues
Actual: infinite loop of requests without any pauses that fail with
`Handling error: InvalidTokenException, Cannot convert access token to JSON` on a backend

**Comment by platosha** [comment] 2018-12-04 13:16
Could be caused by some corrupt `refreshToken` being memoized `localStorage` or something similar.

**Comment by vlukashov** [comment] 2018-12-11 13:32
There is a unit test that verifies corrupt tokens in the local storage do not cause issues.

**Comment by platosha** [comment] 2018-12-11 13:37
Should be fixed in cfea8e7fd6c7974c3358fb377f8c57a8cc9f5a5e

**Comment by upstairlounge** [comment] 2018-12-12 08:11
Expected behaviour

When sending a refresh token to the server and getting an "invalid token" response, the client should not attempt to resend the same token again.

**Comment by manolo** [comment] 2018-12-18 06:52
Able to reproduce, we need to have a non-corrupted but invalid refresh token in localStorage

Steps to reproduce

- Execute this in console 
```
localStorage.setItem('vaadin.connect.refreshToken', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ0ZXN0X2xvZ2luIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImF0aSI6ImI1MWNiZTMwLWMwNzAtNDcxOC04ZTZjLWQxZWVjYTViNGRhNSIsImV4cCI6MTU0NzYzMDAyMSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjE2YzUzYmVlLTJlODAtNDQwMi1iZDI0LWNlMmEzNDM4OTJkMSIsImNsaWVudF9pZCI6InZhYWRpbi1jb25uZWN0LWNsaWVudCJ9.2G50ZV_Q1sA52KWu8ZAVvDLQxQVJM0EIFUc0xSQG5IU');
```
- run test project
- Utilise a service

**Comment by manolo** [comment] 2018-12-18 14:03
double checked, it's fixed in master, not in starter since it does not depend on snapshot.

**Closed by manolo** 2018-12-18 14:03 UTC
Labels: bug, sprint
